# _yaraforge_start.py -- generated by start-nebula.bat, safe to delete
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from database import init_db
init_db()
from app import app
app.run(host='127.0.0.1', port=5002, debug=False)
